# Server
server.port=${PORT:8080}

# PostgreSQL Database (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecuador_db
spring.datasource.username=frank
spring.datasource.password=290307
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:mySecretKey}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Thymeleaf
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true